# *Hospital Readmission Prediction*

### Step1 : Load the the cleaned dataset

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [3]:
df=pd.read_csv(r'C:\\Users\\chidv\\Batch405\\ML\\project1\\Cleaned_data.csv')
df

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med,readmitted
0,[70-80),8,72,1,18,2,0,0,Not specified,Circulatory,Respiratory,Other,no,no,no,yes,no
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes,no
2,[50-60),5,45,0,18,0,0,0,Not specified,Circulatory,Circulatory,Circulatory,no,no,yes,yes,yes
3,[70-80),2,36,0,12,1,0,0,Not specified,Circulatory,Other,Diabetes,no,no,yes,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,[80-90),14,77,1,30,0,0,0,Not specified,Circulatory,Other,Circulatory,no,normal,no,no,yes
24996,[80-90),2,66,0,24,0,0,0,Not specified,Digestive,Injury,Other,no,high,yes,yes,yes
24997,[70-80),5,12,0,6,0,1,0,Not specified,Other,Other,Other,normal,no,no,no,yes
24998,[70-80),2,61,3,15,0,0,0,Family/GeneralPractice,Respiratory,Diabetes,Other,no,no,yes,yes,no
24999,[50-60),10,37,1,24,0,0,0,Not specified,Other,Diabetes,Circulatory,no,no,no,no,yes

### Step 2 : EDA already completed 

-- There assosiations between X, y were present

### Step 3 : Segregating Features X & Target y

In [4]:
X=df.drop('readmitted', axis=1)
y=df.readmitted

In [5]:
X

,age,time_in_hospital,n_lab_procedures,n_procedures,n_medications,n_outpatient,n_inpatient,n_emergency,medical_specialty,diag_1,diag_2,diag_3,glucose_test,A1Ctest,change,diabetes_med
0,[70-80),8,72,1,18,2,0,0,Not specified,Circulatory,Respiratory,Other,no,no,no,yes
1,[70-80),3,34,2,13,0,0,0,Other,Other,Other,Other,no,no,no,yes
2,[50-60),5,45,0,18,0,0,0,Not specified,Circulatory,Circulatory,Circulatory,no,no,yes,yes
3,[70-80),2,36,0,12,1,0,0,Not specified,Circulatory,Other,Diabetes,no,no,yes,yes
4,[60-70),1,42,0,7,0,0,0,InternalMedicine,Other,Circulatory,Respiratory,no,no,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,[80-90),14,77,1,30,0,0,0,Not specified,Circulatory,Other,Circulatory,no,normal,no,no
24996,[80-90),2,66,0,24,0,0,0,Not specified,Digestive,Injury,Other,no,high,yes,yes
24997,[70-80),5,12,0,6,0,1,0,Not specified,Other,Other,Other,normal,no,no,no
24998,[70-80),2,61,3,15,0,0,0,Family/GeneralPractice,Respiratory,Diabetes,Other,no,no,yes,yes
24999,[50-60),10,37,1,24,0,0,0,Not specified,Other,Diabetes,Circulatory,no,no,no,no

## Step 4 :  Test_train_split

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=True, stratify=y, random_state=42)

In [9]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((20000, 16), (5000, 16), (20000,), (5000,))

## Step 5 : Data Transformation

## 5.1 Categorical Encoding

- Since Categorical values are present we convert these categoricals into Numericals, via Categirical Encoding
- All columns except age were nominal values, age belongs to ordinal data

In [10]:
X_train.select_dtypes(exclude='number').columns

Index(['age', 'medical_specialty', 'diag_1', 'diag_2', 'diag_3',
       'glucose_test', 'A1Ctest', 'change', 'diabetes_med'],
      dtype='object')

In [11]:
Nominal_colums=['medical_specialty', 'diag_1', 'diag_2', 'diag_3',
       'glucose_test', 'A1Ctest', 'change', 'diabetes_med']
Ordinal_col=['age']

In [12]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, LabelEncoder

In [13]:
ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
ohe

OneHotEncoder(sparse_output=False)

In [14]:
oe = OrdinalEncoder(
    categories=[[
        '[0-10)','[10-20)','[20-30)','[30-40)','[40-50)',
        '[50-60)','[60-70)','[70-80)','[80-90)','[90-100)'
    ]]).set_output(transform='pandas')

In [15]:
lb=LabelEncoder()

## 5.2 Feature Scaling

In [16]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [17]:
minmax=MinMaxScaler().set_output(transform ='pandas')
StandardScaler=StandardScaler().set_output(transform ='pandas')

In [18]:
StandardScaler

StandardScaler()

## 5.3 Transformation

In [19]:
from sklearn.compose import ColumnTransformer

In [20]:
ct1=ColumnTransformer([('One_Hot_encoding',ohe, Nominal_colums),
                       ('OrdinalEncoding',oe, Ordinal_col)], remainder='passthrough', verbose=True,verbose_feature_names_out = True).set_output(transform='pandas')

In [21]:
ct1

ColumnTransformer(remainder='passthrough',
                  transformers=[('One_Hot_encoding',
                                 OneHotEncoder(sparse_output=False),
                                 ['medical_specialty', 'diag_1', 'diag_2',
                                  'diag_3', 'glucose_test', 'A1Ctest', 'change',
                                  'diabetes_med']),
                                ('OrdinalEncoding',
                                 OrdinalEncoder(categories=[['[0-10)',
                                                             '[10-20)',
                                                             '[20-30)',
                                                             '[30-40)',
                                                             '[40-50)',
                                                             '[50-60)',
                                                             '[60-70)',
                                                             '[70-80)',
                                                             '[80-90)',
                                                             '[90-100)']]),
                                 ['age'])],
                  verbose=True)

In [22]:
#we do NOT apply feature encoders (like OneHot / Ordinal) to the target variable.

X_train_transformed=ct1.fit_transform(X_train)
X_train_transformed
X_test_transformed=ct1.transform(X_test)
X_test_transformed
y_train_transformed=lb.fit_transform(y_train)
y_test_transformed=lb.transform(y_test)

[ColumnTransformer]  (1 of 3) Processing One_Hot_encoding, total=   0.0s
[ColumnTransformer]  (2 of 3) Processing OrdinalEncoding, total=   0.0s
[ColumnTransformer] ..... (3 of 3) Processing remainder, total=   0.0s

In [23]:
y_train_transformed

array([0, 0, 0, ..., 0, 1, 0])

In [24]:
ct2=ColumnTransformer([('StandardScaler',StandardScaler, X_train_transformed.columns)], remainder='passthrough', verbose=True,verbose_feature_names_out = True).set_output(transform='pandas')

In [25]:
ct2

ColumnTransformer(remainder='passthrough',
                  transformers=[('StandardScaler', StandardScaler(),
                                 Index(['One_Hot_encoding__medical_specialty_Cardiology',
       'One_Hot_encoding__medical_specialty_Emergency/Trauma',
       'One_Hot_encoding__medical_specialty_Family/GeneralPractice',
       'One_Hot_encoding__medical_specialty_InternalMedicine',
       'One_Hot_encoding__medical_speci...
       'One_Hot_encoding__A1Ctest_normal', 'One_Hot_encoding__change_no',
       'One_Hot_encoding__change_yes', 'One_Hot_encoding__diabetes_med_no',
       'One_Hot_encoding__diabetes_med_yes', 'OrdinalEncoding__age',
       'remainder__time_in_hospital', 'remainder__n_lab_procedures',
       'remainder__n_procedures', 'remainder__n_medications',
       'remainder__n_outpatient', 'remainder__n_inpatient',
       'remainder__n_emergency'],
      dtype='object'))],
                  verbose=True)

In [26]:
#we do NOT apply Scaling (like minmax / Robust) to the target variable.

X_train_transformed=ct2.fit_transform(X_train_transformed)
X_train_transformed
X_test_transformed=ct2.transform(X_test_transformed)
X_test_transformed

[ColumnTransformer]  (1 of 1) Processing StandardScaler, total=   0.0s

,StandardScaler__One_Hot_encoding__medical_specialty_Cardiology,StandardScaler__One_Hot_encoding__medical_specialty_Emergency/Trauma,StandardScaler__One_Hot_encoding__medical_specialty_Family/GeneralPractice,StandardScaler__One_Hot_encoding__medical_specialty_InternalMedicine,StandardScaler__One_Hot_encoding__medical_specialty_Not specified,StandardScaler__One_Hot_encoding__medical_specialty_Other,StandardScaler__One_Hot_encoding__medical_specialty_Surgery,StandardScaler__One_Hot_encoding__diag_1_Circulatory,StandardScaler__One_Hot_encoding__diag_1_Diabetes,StandardScaler__One_Hot_encoding__diag_1_Digestive,...,StandardScaler__One_Hot_encoding__diabetes_med_no,StandardScaler__One_Hot_encoding__diabetes_med_yes,StandardScaler__OrdinalEncoding__age,StandardScaler__remainder__time_in_hospital,StandardScaler__remainder__n_lab_procedures,StandardScaler__remainder__n_procedures,StandardScaler__remainder__n_medications,StandardScaler__remainder__n_outpatient,StandardScaler__remainder__n_inpatient,StandardScaler__remainder__n_emergency
19284,-0.244022,-0.288425,-0.286488,-0.402887,1.007730,-0.345517,-0.226259,1.485833,-0.274562,-0.320212,...,-0.546536,0.546536,0.498605,-0.145670,-0.064716,-0.787751,-1.020231,-0.315102,-0.522133,-0.217149
9779,-0.244022,-0.288425,-0.286488,-0.402887,1.007730,-0.345517,-0.226259,-0.673023,-0.274562,-0.320212,...,1.829707,-1.829707,0.498605,2.866468,0.692466,-0.203258,0.095928,-0.315102,-0.522133,-0.217149
14788,-0.244022,-0.288425,-0.286488,2.482088,-0.992329,-0.345517,-0.226259,-0.673023,-0.274562,-0.320212,...,1.829707,-1.829707,-1.020838,-0.480352,-1.124772,-0.787751,-1.144248,0.544776,0.331025,-0.217149
19300,-0.244022,-0.288425,-0.286488,-0.402887,1.007730,-0.345517,-0.226259,1.485833,-0.274562,-0.320212,...,-0.546536,0.546536,-1.020838,-0.480352,0.086720,-0.787751,0.343963,-0.315102,-0.522133,-0.217149
23297,-0.244022,-0.288425,-0.286488,2.482088,-0.992329,-0.345517,-0.226259,1.485833,-0.274562,-0.320212,...,-0.546536,0.546536,0.498605,-0.145670,-0.720941,0.965730,-0.400143,-0.315102,-0.522133,-0.217149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4359,-0.244022,-0.288425,3.490547,-0.402887,-0.992329,-0.345517,-0.226259,-0.673023,-0.274562,-0.320212,...,-0.546536,0.546536,0.498605,-0.480352,-1.881954,-0.787751,0.219945,-0.315102,-0.522133,-0.217149
18094,-0.244022,-0.288425,-0.286488,-0.402887,1.007730,-0.345517,-0.226259,-0.673023,-0.274562,3.122929,...,-0.546536,0.546536,-0.261116,-1.149717,-2.083869,0.381236,0.219945,-0.315102,-0.522133,-0.217149
2647,-0.244022,-0.288425,-0.286488,-0.402887,1.007730,-0.345517,-0.226259,1.485833,-0.274562,-0.320212,...,-0.546536,0.546536,1.258327,1.527740,0.944860,1.550223,2.700296,2.264533,0.331025,-0.217149
23390,-0.244022,-0.288425,-0.286488,-0.402887,1.007730,-0.345517,-0.226259,-0.673023,-0.274562,-0.320212,...,-0.546536,0.546536,-0.261116,-0.145670,0.187678,-0.787751,-0.896213,-0.315102,0.331025,-0.217149
20040,4.097999,-0.288425,-0.286488,-0.402887,-0.992329,-0.345517,-0.226259,-0.673023,-0.274562,-0.320212,...,-0.546536,0.546536,0.498605,0.189012,1.045818,-0.787751,-0.276125,-0.315102,-0.522133,-0.217149

# Step 6:  MODEL BUILDING

In [27]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
import xgboost as xgb
from xgboost import XGBClassifier, XGBRegressor
from sklearn.linear_model import LogisticRegression

In [28]:
print('f25hi')

f25hi

In [29]:
Random_Forest=RandomForestClassifier(n_estimators=100,random_state=42)
Logistic_Regression = LogisticRegression(max_iter=1000)
KNN=KNeighborsClassifier(n_neighbors=3,weights='uniform')
Decision_Tree=DecisionTreeClassifier()
Support_Vector=svm.SVC()
XGB=XGBClassifier()

In [30]:
def Pre_model_Analysis(Model,X_train_transformed,X_test_transformed,y_train,y_test):
    Model.fit(X_train_transformed,y_train)
    BS=Model.score(X_train_transformed,y_train)
    Y_pred=Model.predict(X_test_transformed)
    return f'Training score of {Model.__class__.__name__} is : {BS}       Testing score of {Model} is : {accuracy_score(y_test, Y_pred)}'

In [32]:
models=[Random_Forest, Logistic_Regression, KNN, Decision_Tree, Support_Vector]
for every in models:
    X=Pre_model_Analysis(every, X_train_transformed,X_test_transformed,y_train_transformed,y_test_transformed)
    print(X)

Training score of RandomForestClassifier is : 1.0       Testing score of RandomForestClassifier(random_state=42) is : 0.6002
Training score of LogisticRegression is : 0.6139       Testing score of LogisticRegression(max_iter=1000) is : 0.611
Training score of KNeighborsClassifier is : 0.76735       Testing score of KNeighborsClassifier(n_neighbors=3) is : 0.545
Training score of DecisionTreeClassifier is : 1.0       Testing score of DecisionTreeClassifier() is : 0.5426
Training score of SVC is : 0.6756       Testing score of SVC() is : 0.6094

## There fore train and test Score are very low due to minimal combination of parameters which give maximum result, we deal them by `HYPER PARAMETER TUNING` with Cross validation

In [41]:
import optuna
from sklearn.model_selection import StratifiedKFold
from optuna.samplers import TPESampler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder

# Hyper Parameter Tuning

### Using `accuracy score` Metrics

In [45]:
def Objective(trail):
    model=trail.suggest_categorical('model',['KNN','Decision_Tree','Logistic_Regression','Random_Forest','XGBoost'])
    if model=='KNN':
        n_neighbors=trail.suggest_int('n_neighbors',1,10)
        weights=trail.suggest_categorical('weights',['uniform','distance'])
        OBJ=KNeighborsClassifier(n_neighbors=n_neighbors,weights=weights)
    elif model=='Decision_Tree':
        criterion=trail.suggest_categorical('criterion',["gini","entropy","log_loss"])
        dt_min_samples_leaf=trail.suggest_int('dt_min_samples_leaf',2,10)
        max_leaf_nodes=trail.suggest_int('max_leaf_nodes',2,10)
        dt_min_samples_split=trail.suggest_int('dt_min_samples_split',2,10)
        dt_max_depth=trail.suggest_int('dt_max_depth',2,10)
        OBJ=DecisionTreeClassifier(criterion=criterion,min_samples_leaf=dt_min_samples_leaf,max_leaf_nodes=max_leaf_nodes,min_samples_split=dt_min_samples_split,max_depth=dt_max_depth)
    elif model=='Logistic_Regression':
        l1_ratio=trail.suggest_float('l1_ratio',0.0,1.0)
        lr_C=trail.suggest_float('lr_C',1e-4,100,log=True)
        solver=trail.suggest_categorical('solver',['lbfgs','newton-cg','saga'])
        lr_max_iter=trail.suggest_int('lr_max_iter',200,2000)
        lr_class_weight=trail.suggest_categorical('lr_class_weight',[None,'balanced'])
        OBJ = LogisticRegression(C=lr_C, solver=solver, max_iter=lr_max_iter, class_weight=lr_class_weight, random_state=42 )
    elif model=='Random_Forest':
        rf_n_estimators=trail.suggest_int('rf_n_estimators',100,1000)
        rf_max_depth=trail.suggest_int('rf_max_depth',2,50)
        rf_min_samples_split=trail.suggest_int('rf_min_samples_split',2,50)
        rf_min_samples_leaf=trail.suggest_int('rf_min_samples_leaf',1,20)
        max_features=trail.suggest_categorical('max_features',['sqrt','log2',None])
        bootstrap=trail.suggest_categorical('bootstrap',[True,False])
        rf_class_weight=trail.suggest_categorical('rf_class_weight',[None,'balanced','balanced_subsample'])
        OBJ=RandomForestClassifier(n_estimators=rf_n_estimators,max_depth=rf_max_depth,min_samples_split=rf_min_samples_split,min_samples_leaf=rf_min_samples_leaf,max_features=max_features,bootstrap=bootstrap,class_weight=rf_class_weight,random_state=42,n_jobs=-1)
    elif model=='XGBoost':
        xgb_n_estimators=trail.suggest_int('xgb_n_estimators',100,1000)
        xgb_max_depth=trail.suggest_int('xgb_max_depth',2,15)
        learning_rate=trail.suggest_float('learning_rate',0.001,0.3,log=True)
        subsample=trail.suggest_float('subsample',0.5,1.0)
        colsample_bytree=trail.suggest_float('colsample_bytree',0.5,1.0)
        xgb_gamma=trail.suggest_float('xgb_gamma',0.0,5.0)
        xgb_min_child_weight=trail.suggest_int('xgb_min_child_weight',1,10)
        reg_alpha=trail.suggest_float('reg_alpha',1e-8,10,log=True)
        reg_lambda=trail.suggest_float('reg_lambda',1e-8,10,log=True)
        OBJ=XGBClassifier(n_estimators=xgb_n_estimators,max_depth=xgb_max_depth,learning_rate=learning_rate,subsample=subsample,colsample_bytree=colsample_bytree,gamma=xgb_gamma,min_child_weight=xgb_min_child_weight,reg_alpha=reg_alpha,reg_lambda=reg_lambda,random_state=42,n_jobs=-1,eval_metric='logloss')

    cv1=StratifiedKFold(n_splits=8,shuffle=True,random_state=42)
    score=cross_val_score(estimator=OBJ,X=X_train_transformed,y=y_train_transformed,scoring='accuracy',cv=cv1).mean()
    return score

In [47]:
## Create a study 
study=optuna.create_study(direction='maximize',  study_name='Baysenj11',sampler=TPESampler())

[I 2026-03-12 11:45:08,022] A new study created in memory with name: Baysenj11

In [48]:
## Optimize

study.optimize(Objective,n_trials=100)

[I 2026-03-12 11:45:28,130] Trial 0 finished with value: 0.60945 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 574, 'rf_max_depth': 4, 'rf_min_samples_split': 14, 'rf_min_samples_leaf': 14, 'max_features': 'sqrt', 'bootstrap': False, 'rf_class_weight': 'balanced_subsample'}. Best is trial 0 with value: 0.60945.
[I 2026-03-12 11:46:42,247] Trial 1 finished with value: 0.61355 and parameters: {'model': 'XGBoost', 'xgb_n_estimators': 675, 'xgb_max_depth': 7, 'learning_rate': 0.0010971345939689364, 'subsample': 0.8226265836372801, 'colsample_bytree': 0.6923143135311107, 'xgb_gamma': 1.8081620094420459, 'xgb_min_child_weight': 6, 'reg_alpha': 0.0013442199941997792, 'reg_lambda': 2.8698506608772197e-08}. Best is trial 1 with value: 0.61355.
[I 2026-03-12 11:46:42,754] Trial 2 finished with value: 0.60595 and parameters: {'model': 'Decision_Tree', 'criterion': 'entropy', 'dt_min_samples_leaf': 8, 'max_leaf_nodes': 9, 'dt_min_samples_split': 6, 'dt_max_depth': 10}. Best is trial 1 with value: 0.61355.
[I 2026-03-12 11:46:43,542] Trial 3 finished with value: 0.607 and parameters: {'model': 'Logistic_Regression', 'l1_ratio': 0.00040906785305261373, 'lr_C': 0.0007106576527685309, 'solver': 'newton-cg', 'lr_max_iter': 1716, 'lr_class_weight': None}. Best is trial 1 with value: 0.61355.
[I 2026-03-12 11:46:45,489] Trial 4 finished with value: 0.55445 and parameters: {'model': 'KNN', 'n_neighbors': 9, 'weights': 'uniform'}. Best is trial 1 with value: 0.61355.
[I 2026-03-12 11:47:19,738] Trial 5 finished with value: 0.61475 and parameters: {'model': 'XGBoost', 'xgb_n_estimators': 429, 'xgb_max_depth': 6, 'learning_rate': 0.1327155278517413, 'subsample': 0.9243107906274106, 'colsample_bytree': 0.6006813041635536, 'xgb_gamma': 4.568585627292129, 'xgb_min_child_weight': 5, 'reg_alpha': 0.055897217923683296, 'reg_lambda': 1.8489407843124628}. Best is trial 5 with value: 0.61475.
[I 2026-03-12 11:47:20,239] Trial 6 finished with value: 0.6061000000000001 and parameters: {'model': 'Decision_Tree', 'criterion': 'entropy', 'dt_min_samples_leaf': 6, 'max_leaf_nodes': 6, 'dt_min_samples_split': 9, 'dt_max_depth': 6}. Best is trial 5 with value: 0.61475.
[I 2026-03-12 11:47:29,879] Trial 7 finished with value: 0.62 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 190, 'rf_max_depth': 21, 'rf_min_samples_split': 48, 'rf_min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 7 with value: 0.62.
[I 2026-03-12 11:47:30,255] Trial 8 finished with value: 0.6071500000000001 and parameters: {'model': 'Logistic_Regression', 'l1_ratio': 0.5972099938885822, 'lr_C': 0.0002289028270121132, 'solver': 'lbfgs', 'lr_max_iter': 899, 'lr_class_weight': 'balanced'}. Best is trial 7 with value: 0.62.
[I 2026-03-12 11:48:08,601] Trial 9 finished with value: 0.6133 and parameters: {'model': 'XGBoost', 'xgb_n_estimators': 314, 'xgb_max_depth': 6, 'learning_rate': 0.0020570923822078482, 'subsample': 0.8519437497485761, 'colsample_bytree': 0.855558784078067, 'xgb_gamma': 3.851051496488485, 'xgb_min_child_weight': 4, 'reg_alpha': 0.18797715812120158, 'reg_lambda': 6.593228489964967e-07}. Best is trial 7 with value: 0.62.
[I 2026-03-12 11:48:14,379] Trial 10 finished with value: 0.6198 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 119, 'rf_max_depth': 34, 'rf_min_samples_split': 50, 'rf_min_samples_leaf': 19, 'max_features': 'log2', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 7 with value: 0.62.
[I 2026-03-12 11:48:19,219] Trial 11 finished with value: 0.6174 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 101, 'rf_max_depth': 35, 'rf_min_samples_split': 50, 'rf_min_samples_leaf': 20, 'max_features': 'log2', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 7 with value: 0.62.
[I 2026-03-12 11:48:25,542] Trial 12 finished with value: 0.6201000000000001 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 115, 'rf_max_depth': 25, 'rf_min_samples_split': 50, 'rf_min_samples_leaf': 20, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 12 with value: 0.6201000000000001.
[I 2026-03-12 11:48:40,875] Trial 13 finished with value: 0.62005 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 289, 'rf_max_depth': 17, 'rf_min_samples_split': 37, 'rf_min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 12 with value: 0.6201000000000001.
[I 2026-03-12 11:49:00,168] Trial 14 finished with value: 0.621 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 387, 'rf_max_depth': 16, 'rf_min_samples_split': 32, 'rf_min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:49:01,222] Trial 15 finished with value: 0.5372 and parameters: {'model': 'KNN', 'n_neighbors': 1, 'weights': 'distance'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:51:56,378] Trial 16 finished with value: 0.6108 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 949, 'rf_max_depth': 49, 'rf_min_samples_split': 26, 'rf_min_samples_leaf': 2, 'max_features': None, 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:52:15,071] Trial 17 finished with value: 0.6199999999999999 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 441, 'rf_max_depth': 11, 'rf_min_samples_split': 30, 'rf_min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': False, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:52:59,348] Trial 18 finished with value: 0.6169 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 474, 'rf_max_depth': 29, 'rf_min_samples_split': 2, 'rf_min_samples_leaf': 8, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced_subsample'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:52:59,567] Trial 19 finished with value: 0.6032 and parameters: {'model': 'Decision_Tree', 'criterion': 'gini', 'dt_min_samples_leaf': 2, 'max_leaf_nodes': 2, 'dt_min_samples_split': 2, 'dt_max_depth': 2}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:53:00,589] Trial 20 finished with value: 0.54295 and parameters: {'model': 'KNN', 'n_neighbors': 3, 'weights': 'distance'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:53:17,247] Trial 21 finished with value: 0.6199999999999999 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 319, 'rf_max_depth': 17, 'rf_min_samples_split': 36, 'rf_min_samples_leaf': 1, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:53:33,776] Trial 22 finished with value: 0.6195 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 319, 'rf_max_depth': 18, 'rf_min_samples_split': 39, 'rf_min_samples_leaf': 4, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:53:48,210] Trial 23 finished with value: 0.61755 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 303, 'rf_max_depth': 11, 'rf_min_samples_split': 39, 'rf_min_samples_leaf': 14, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\chidv\.conda\envs\batch405\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2026-03-12 11:54:06,341] Trial 24 finished with value: 0.6111 and parameters: {'model': 'Logistic_Regression', 'l1_ratio': 0.9883063260644431, 'lr_C': 93.5003214720454, 'solver': 'saga', 'lr_max_iter': 208, 'lr_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:55:55,506] Trial 25 finished with value: 0.6131 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 638, 'rf_max_depth': 26, 'rf_min_samples_split': 27, 'rf_min_samples_leaf': 4, 'max_features': None, 'bootstrap': True, 'rf_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:56:06,764] Trial 26 finished with value: 0.61975 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 247, 'rf_max_depth': 13, 'rf_min_samples_split': 42, 'rf_min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': False, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:56:28,677] Trial 27 finished with value: 0.61685 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 424, 'rf_max_depth': 24, 'rf_min_samples_split': 32, 'rf_min_samples_leaf': 14, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:56:54,556] Trial 28 finished with value: 0.6125 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 697, 'rf_max_depth': 4, 'rf_min_samples_split': 21, 'rf_min_samples_leaf': 11, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:57:01,990] Trial 29 finished with value: 0.6167 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 183, 'rf_max_depth': 32, 'rf_min_samples_split': 43, 'rf_min_samples_leaf': 1, 'max_features': 'log2', 'bootstrap': True, 'rf_class_weight': 'balanced'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:57:02,239] Trial 30 finished with value: 0.6032 and parameters: {'model': 'Decision_Tree', 'criterion': 'log_loss', 'dt_min_samples_leaf': 10, 'max_leaf_nodes': 2, 'dt_min_samples_split': 2, 'dt_max_depth': 2}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:57:11,728] Trial 31 finished with value: 0.6204500000000001 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 229, 'rf_max_depth': 21, 'rf_min_samples_split': 45, 'rf_min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 11:57:26,099] Trial 32 finished with value: 0.62075 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 368, 'rf_max_depth': 18, 'rf_min_samples_split': 45, 'rf_min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:01:16,983] Trial 33 finished with value: 0.5721499999999999 and parameters: {'model': 'XGBoost', 'xgb_n_estimators': 972, 'xgb_max_depth': 15, 'learning_rate': 0.12492149412056264, 'subsample': 0.5097573387435108, 'colsample_bytree': 0.9680279470329496, 'xgb_gamma': 0.5175988719646927, 'xgb_min_child_weight': 10, 'reg_alpha': 3.664441284770828e-08, 'reg_lambda': 4.920872593469497}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:01:31,820] Trial 34 finished with value: 0.62025 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 378, 'rf_max_depth': 23, 'rf_min_samples_split': 45, 'rf_min_samples_leaf': 18, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:01:32,607] Trial 35 finished with value: 0.6109 and parameters: {'model': 'Logistic_Regression', 'l1_ratio': 0.0031922657198010795, 'lr_C': 2.66564758218029, 'solver': 'newton-cg', 'lr_max_iter': 1864, 'lr_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:01:34,723] Trial 36 finished with value: 0.55445 and parameters: {'model': 'KNN', 'n_neighbors': 9, 'weights': 'uniform'}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:01:51,725] Trial 37 finished with value: 0.62035 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 428, 'rf_max_depth': 19, 'rf_min_samples_split': 44, 'rf_min_samples_leaf': 17, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:01:57,618] Trial 38 finished with value: 0.6102000000000001 and parameters: {'model': 'XGBoost', 'xgb_n_estimators': 129, 'xgb_max_depth': 2, 'learning_rate': 0.013100985515857096, 'subsample': 0.5709240722490502, 'colsample_bytree': 0.5057410516927213, 'xgb_gamma': 2.652455402339537, 'xgb_min_child_weight': 1, 'reg_alpha': 1.5704078561932994e-08, 'reg_lambda': 0.0006273331792499676}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:01:58,102] Trial 39 finished with value: 0.6052 and parameters: {'model': 'Decision_Tree', 'criterion': 'gini', 'dt_min_samples_leaf': 2, 'max_leaf_nodes': 10, 'dt_min_samples_split': 10, 'dt_max_depth': 10}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:03:02,810] Trial 40 finished with value: 0.61685 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 493, 'rf_max_depth': 13, 'rf_min_samples_split': 45, 'rf_min_samples_leaf': 17, 'max_features': None, 'bootstrap': True, 'rf_class_weight': None}. Best is trial 14 with value: 0.621.
[I 2026-03-12 12:03:17,631] Trial 41 finished with value: 0.6221 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 369, 'rf_max_depth': 20, 'rf_min_samples_split': 43, 'rf_min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:03:32,670] Trial 42 finished with value: 0.62005 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 370, 'rf_max_depth': 19, 'rf_min_samples_split': 42, 'rf_min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:03:54,324] Trial 43 finished with value: 0.6214999999999999 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 523, 'rf_max_depth': 16, 'rf_min_samples_split': 34, 'rf_min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:04:23,719] Trial 44 finished with value: 0.6205 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 555, 'rf_max_depth': 14, 'rf_min_samples_split': 34, 'rf_min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:04:30,566] Trial 45 finished with value: 0.6110500000000001 and parameters: {'model': 'Logistic_Regression', 'l1_ratio': 0.5438868776019559, 'lr_C': 0.04264497032917876, 'solver': 'saga', 'lr_max_iter': 956, 'lr_class_weight': 'balanced'}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:04:50,396] Trial 46 finished with value: 0.61605 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 563, 'rf_max_depth': 9, 'rf_min_samples_split': 33, 'rf_min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': False, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:05:30,028] Trial 47 finished with value: 0.621 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 720, 'rf_max_depth': 15, 'rf_min_samples_split': 36, 'rf_min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:08:44,211] Trial 48 finished with value: 0.60605 and parameters: {'model': 'XGBoost', 'xgb_n_estimators': 758, 'xgb_max_depth': 15, 'learning_rate': 0.015558346667834967, 'subsample': 0.6769141329361643, 'colsample_bytree': 0.7939382334228343, 'xgb_gamma': 0.26043070273328883, 'xgb_min_child_weight': 10, 'reg_alpha': 7.327456239764201e-06, 'reg_lambda': 0.000583480643398419}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:08:46,034] Trial 49 finished with value: 0.55145 and parameters: {'model': 'KNN', 'n_neighbors': 6, 'weights': 'distance'}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:09:33,154] Trial 50 finished with value: 0.62205 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 782, 'rf_max_depth': 14, 'rf_min_samples_split': 39, 'rf_min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:10:12,457] Trial 51 finished with value: 0.61685 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 801, 'rf_max_depth': 8, 'rf_min_samples_split': 39, 'rf_min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:10:57,689] Trial 52 finished with value: 0.62045 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 837, 'rf_max_depth': 15, 'rf_min_samples_split': 28, 'rf_min_samples_leaf': 15, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:11:25,341] Trial 53 finished with value: 0.6122000000000001 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 718, 'rf_max_depth': 7, 'rf_min_samples_split': 36, 'rf_min_samples_leaf': 13, 'max_features': 'sqrt', 'bootstrap': False, 'rf_class_weight': 'balanced_subsample'}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:12:19,653] Trial 54 finished with value: 0.6168 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 628, 'rf_max_depth': 16, 'rf_min_samples_split': 23, 'rf_min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': 'balanced_subsample'}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:13:01,294] Trial 55 finished with value: 0.6205 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 809, 'rf_max_depth': 21, 'rf_min_samples_split': 31, 'rf_min_samples_leaf': 14, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:13:01,785] Trial 56 finished with value: 0.6061000000000001 and parameters: {'model': 'Decision_Tree', 'criterion': 'log_loss', 'dt_min_samples_leaf': 5, 'max_leaf_nodes': 6, 'dt_min_samples_split': 6, 'dt_max_depth': 6}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:13:19,100] Trial 57 finished with value: 0.61785 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 371, 'rf_max_depth': 12, 'rf_min_samples_split': 40, 'rf_min_samples_leaf': 10, 'max_features': 'log2', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.
[I 2026-03-12 12:14:07,943] Trial 58 finished with value: 0.62095 and parameters: {'model': 'Random_Forest', 'rf_n_estimators': 878, 'rf_max_depth': 21, 'rf_min_samples_split': 35, 'rf_min_samples_leaf': 16, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}. Best is trial 41 with value: 0.6221.

In [49]:

print('Best Score :',study.best_value)
print('Best Params:',study.best_params)

Best Score : 0.62345
Best Params: {'model': 'Random_Forest', 'rf_n_estimators': 489, 'rf_max_depth': 42, 'rf_min_samples_split': 38, 'rf_min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}

### HyperParameter Tuning Using `F1 score ` Metrics

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1=f1_score()

In [56]:
def Objective(trail):
    model=trail.suggest_categorical('model',['KNN','Decision_Tree','Logistic_Regression','Random_Forest','XGBoost'])
    if model=='KNN':
        n_neighbors=trail.suggest_int('n_neighbors',1,10)
        weights=trail.suggest_categorical('weights',['uniform','distance'])
        OBJ=KNeighborsClassifier(n_neighbors=n_neighbors,weights=weights)
    elif model=='Decision_Tree':
        criterion=trail.suggest_categorical('criterion',["gini","entropy","log_loss"])
        dt_min_samples_leaf=trail.suggest_int('dt_min_samples_leaf',2,10)
        max_leaf_nodes=trail.suggest_int('max_leaf_nodes',2,10)
        dt_min_samples_split=trail.suggest_int('dt_min_samples_split',2,10)
        dt_max_depth=trail.suggest_int('dt_max_depth',2,10)
        OBJ=DecisionTreeClassifier(criterion=criterion,min_samples_leaf=dt_min_samples_leaf,max_leaf_nodes=max_leaf_nodes,min_samples_split=dt_min_samples_split,max_depth=dt_max_depth)
    elif model=='Logistic_Regression':
        l1_ratio=trail.suggest_float('l1_ratio',0.0,1.0)
        lr_C=trail.suggest_float('lr_C',1e-4,100,log=True)
        solver=trail.suggest_categorical('solver',['lbfgs','newton-cg','saga'])
        lr_max_iter=trail.suggest_int('lr_max_iter',200,2000)
        lr_class_weight=trail.suggest_categorical('lr_class_weight',[None,'balanced'])
        OBJ = LogisticRegression(C=lr_C, solver=solver, max_iter=lr_max_iter, class_weight=lr_class_weight, random_state=42 )
    elif model=='Random_Forest':
        rf_n_estimators=trail.suggest_int('rf_n_estimators',100,1000)
        rf_max_depth=trail.suggest_int('rf_max_depth',2,50)
        rf_min_samples_split=trail.suggest_int('rf_min_samples_split',2,50)
        rf_min_samples_leaf=trail.suggest_int('rf_min_samples_leaf',1,20)
        max_features=trail.suggest_categorical('max_features',['sqrt','log2',None])
        bootstrap=trail.suggest_categorical('bootstrap',[True,False])
        rf_class_weight=trail.suggest_categorical('rf_class_weight',[None,'balanced','balanced_subsample'])
        OBJ=RandomForestClassifier(n_estimators=rf_n_estimators,max_depth=rf_max_depth,min_samples_split=rf_min_samples_split,min_samples_leaf=rf_min_samples_leaf,max_features=max_features,bootstrap=bootstrap,class_weight=rf_class_weight,random_state=42,n_jobs=-1)
    elif model=='XGBoost':
        xgb_n_estimators=trail.suggest_int('xgb_n_estimators',100,1000)
        xgb_max_depth=trail.suggest_int('xgb_max_depth',2,15)
        learning_rate=trail.suggest_float('learning_rate',0.001,0.3,log=True)
        subsample=trail.suggest_float('subsample',0.5,1.0)
        colsample_bytree=trail.suggest_float('colsample_bytree',0.5,1.0)
        xgb_gamma=trail.suggest_float('xgb_gamma',0.0,5.0)
        xgb_min_child_weight=trail.suggest_int('xgb_min_child_weight',1,10)
        reg_alpha=trail.suggest_float('reg_alpha',1e-8,10,log=True)
        reg_lambda=trail.suggest_float('reg_lambda',1e-8,10,log=True)
        OBJ=XGBClassifier(n_estimators=xgb_n_estimators,max_depth=xgb_max_depth,learning_rate=learning_rate,subsample=subsample,colsample_bytree=colsample_bytree,gamma=xgb_gamma,min_child_weight=xgb_min_child_weight,reg_alpha=reg_alpha,reg_lambda=reg_lambda,random_state=42,n_jobs=-1,eval_metric='logloss')

    cv1=StratifiedKFold(n_splits=8,shuffle=True,random_state=42)
    score=cross_val_score(estimator=OBJ,X=X_train_transformed,y=y_train_transformed,scoring='f1',cv=cv1).mean()
    return score

In [57]:
## Create a study 
study2=optuna.create_study(direction='maximize',  study_name='F1_Metrics',sampler=TPESampler())

[I 2026-03-12 12:45:49,131] A new study created in memory with name: F1_Metrics

In [ ]:
study2.optimize(Objective,n_trials=100)

In [59]:
# 
print('Best Score :',study2.best_value)
print('Best Params:',study2.best_params)

Best Score : 0.5903877049959398
Best Params: {'model': 'Random_Forest', 'rf_n_estimators': 188, 'rf_max_depth': 40, 'rf_min_samples_split': 45, 'rf_min_samples_leaf': 12, 'max_features': 'sqrt', 'bootstrap': False, 'rf_class_weight': 'balanced_subsample'}

## After comparing different models based on Accuracy and F1 Score, the Random Forest model performed the best among all the models tested. Therefore, Random Forest was selected as the final model.

### Using hyperparameter optimization, the following parameters were identified as the best configuration for the Random Forest model.

### The model achieved an accuracy of approximately 62% on the real test data.

In [61]:
selected_params={'model': 'Random_Forest', 'rf_n_estimators': 489, 'rf_max_depth': 42, 'rf_min_samples_split': 38, 'rf_min_samples_leaf': 6, 'max_features': 'sqrt', 'bootstrap': True, 'rf_class_weight': None}
selected_params

{'model': 'Random_Forest',
 'rf_n_estimators': 489,
 'rf_max_depth': 42,
 'rf_min_samples_split': 38,
 'rf_min_samples_leaf': 6,
 'max_features': 'sqrt',
 'bootstrap': True,
 'rf_class_weight': None}

## Since we used unique parameter names for each model , to avoid overlapping b/w other models , we need to clearly redefine correct parms

In [ ]:
RandomForestClassifier(

In [88]:
RF = RandomForestClassifier(
            n_estimators=489,
            max_depth=42,
            min_samples_split=38,
            min_samples_leaf=6,
            max_features='sqrt',
            bootstrap=True,
            class_weight=None,
            random_state=42
            
)

In [89]:
RF.fit(X_train_transformed,y_train_transformed)

RandomForestClassifier(max_depth=42, min_samples_leaf=6, min_samples_split=38,
                       n_estimators=489, random_state=42)

# Step 7:  Model Evaluation

### Training Score :

In [90]:
RF.score(X_train_transformed,y_train_transformed)

0.7246

### Testing Score :

In [91]:
from sklearn.metrics import accuracy_score, f1_score

In [92]:
y_pred=RF.predict(X_test_transformed)

In [93]:
accuracy_score(y_test_transformed,y_pred)

0.6174

# Step 8: Pipeline + Save .pkl

In [97]:
from sklearn.pipeline import Pipeline
import joblib

full_pipeline = Pipeline(steps=[
    ('encoding', ct1),   
    ('scaling',  ct2),   
    ('model',    RF)    
])

full_pipeline.fit(X_train, y_train_transformed)

y_pred_pipeline = full_pipeline.predict(X_test)
print("Test Accuracy :", accuracy_score(y_test_transformed, y_pred_pipeline))

# Save
joblib.dump(full_pipeline, 'hospital_readmission_pipeline.pkl')
joblib.dump(lb,            'label_encoder.pkl')

print("Saved → hospital_readmission_pipeline.pkl")
print("Saved → label_encoder.pkl")

[ColumnTransformer]  (1 of 3) Processing One_Hot_encoding, total=   0.1s
[ColumnTransformer]  (2 of 3) Processing OrdinalEncoding, total=   0.0s
[ColumnTransformer] ..... (3 of 3) Processing remainder, total=   0.0s
[ColumnTransformer]  (1 of 1) Processing StandardScaler, total=   0.0s
Test Accuracy : 0.6174
Saved → hospital_readmission_pipeline.pkl
Saved → label_encoder.pkl

In [6]:
import joblib

# Load your existing pkl
with open('hospital_readmission_pipeline.pkl', 'rb') as f:
    import pickle
    model = pickle.load(f)

# Re-save with joblib
joblib.dump(model, 'hospital_readmission_pipeline1.pkl')
print("✅ Done")

UnpicklingError: STACK_GLOBAL requires str

In [7]:
import sys, sklearn
print("Python:", sys.version)
print("Sklearn:", sklearn.__version__)

Python: 3.12.9 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 18:49:16) [MSC v.1929 64 bit (AMD64)]
Sklearn: 1.8.0